---
title: "Part 1"
author: "Peyton Moore"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```


### Detect string patterns with `str_detect()`

```{r}
vec <- c(" A Unicorn    Fish",  "add   cornmeal", "french FRIEs", "acorn Squash")

str_detect(vec, pattern = "corn")

#View(starwars)
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))

walk_subset


# use str_subset()
# pretty much the same as filter + str_detect but can use if we want 
```
### Replace a string pattern with something else

`str_replace()` to replace an existing string pattern with something else.

```{r}

vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")

vec_bren

```

replace the pattern "Sky" with the pattern "TORNADO"

```{r}
sw_tornado <- starwars %>% 
  mutate( name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```


### Use `str_trim()` to remove excess leading and trailing whitespace

```{r}
str_trim(vec)

str_squish(vec)


str_to_lower(vec)

str_to_upper(vec)

str_to_title(vec)
```

Using these in combination:

```{r}

sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))


```

